# for a description of available keys, see https://github.com/typst/packages/?tab=readme-ov-file#package-format

[package]
name = "blorem"
version = "99.99.99"
entrypoint = "src/lib.typ"
authors = [
  "Luiz Georg <https://github.com/mentonin>"
]
license = "GPL-3.0-or-later"
description = "Better lorem."
repository = "https://github.com/mentonin/blorem"
keywords = [
  "placeholder",
  "lorem",
  "blind text",
  "lipsum",
]
categories = [
  "text",
  "utility",
]
compiler = "0.13"

exclude = [
  ".github",
  "scripts",
  "tests",
  ".typstignore",
  "Justfile",
  "wasm",
]
